/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 23-апр-2016 19:14:19 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `food_categories` CASCADE
;

DROP TABLE IF EXISTS `food_orders` CASCADE
;

DROP TABLE IF EXISTS `foods` CASCADE
;

DROP TABLE IF EXISTS `orders` CASCADE
;

DROP TABLE IF EXISTS `sessions` CASCADE
;

DROP TABLE IF EXISTS `shops` CASCADE
;

DROP TABLE IF EXISTS `users` CASCADE
;

/* Create Tables */

CREATE TABLE `food_categories`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) 	 NULL,
	`shop_id` INTEGER 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_food_categories` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `food_orders`
(
	`id` INTEGER NOT NULL,
	`price` INT 	 NULL,
	`quantity` INTEGER 	 NULL,
	`food_id` INTEGER 	 NULL,
	`order_id` INTEGER 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_food_orders` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `foods`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`description` TEXT 	 NULL,
	`image_url` TEXT 	 NULL,
	`price` INTEGER 	 NULL,
	`shop_id` INT 	 NULL,
	`category_id` INTEGER 	 NULL,
	`created_at` DATETIME 	 NULL,
	`update_at` DATETIME 	 NULL,
	CONSTRAINT `PK_foods` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `orders`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`price` INT 	 NULL,
	`is_payed` BOOL 	 NULL,
	`session_id` INTEGER 	 NULL,
	`user_id` INTEGER 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_orders` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `sessions`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`shop_id` INTEGER 	 NULL,
	`order_time` DATETIME 	 NULL,
	`delivery_time` DATETIME 	 NULL,
	`address` TEXT 	 NULL,
	`price` INT 	 NULL,
	`user_id` INTEGER 	 NULL,
	`status` TINYINT NOT NULL DEFAULT 0,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_sessions` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `shops`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`site_url` TEXT 	 NULL,
	`logo_url` TEXT 	 NULL,
	`description` TEXT 	 NULL,
	`delivery_price` INT 	 NULL,
	`min_order_price` INT 	 NULL,
	`min_free_delivery_time` TIME 	 NULL,
	`delivery_time` TEXT 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_shops` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `users`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(100) 	 NULL,
	`last_name` VARCHAR(100) 	 NULL,
	`email` VARCHAR(250) 	 NULL,
	`phone` VARCHAR(50) 	 NULL,
	`payment_option` TINYINT 	 NULL,
	`address` TEXT 	 NULL,
	`avatar_url` TEXT 	 NULL,
	`registration_service` INTEGER NOT NULL,
	`external_user_id` BIGINT NOT NULL,
	`token` VARCHAR(50) 	 NULL,
	`token_expires_at` DATETIME 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_users` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `food_categories` 
 ADD INDEX `IXFK_food_categories_shops` (`shop_id` ASC)
;

ALTER TABLE `food_orders` 
 ADD INDEX `IXFK_order_items_foods` (`food_id` ASC)
;

ALTER TABLE `food_orders` 
 ADD INDEX `IXFK_order_items_order_part` (`order_id` ASC)
;

ALTER TABLE `foods` 
 ADD INDEX `IXFK_foods_food_categories` (`category_id` ASC)
;

ALTER TABLE `foods` 
 ADD INDEX `IXFK_foods_shops` (`shop_id` ASC)
;

ALTER TABLE `orders` 
 ADD INDEX `IXFK_orders_sessions` (`session_id` ASC)
;

ALTER TABLE `orders` 
 ADD INDEX `IXFK_orders_users` (`user_id` ASC)
;

ALTER TABLE `sessions` 
 ADD INDEX `IXFK_sessions_shops` (`shop_id` ASC)
;

ALTER TABLE `sessions` 
 ADD INDEX `IXFK_sessions_users` (`user_id` ASC)
;

ALTER TABLE `sessions` 
 ADD INDEX `IX_status` (`status` ASC)
;

ALTER TABLE `shops` 
 ADD INDEX `IX_name` (`name` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IX_external` (`registration_service` ASC, `external_user_id` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IX_email` (`email` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `food_orders` 
 ADD CONSTRAINT `FK_order_items_foods`
	FOREIGN KEY (`food_id`) REFERENCES `foods` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `food_orders` 
 ADD CONSTRAINT `FK_order_items_order_part`
	FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `foods` 
 ADD CONSTRAINT `FK_foods_food_categories`
	FOREIGN KEY (`category_id`) REFERENCES `food_categories` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `foods` 
 ADD CONSTRAINT `FK_foods_shops`
	FOREIGN KEY (`shop_id`) REFERENCES `shops` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `orders` 
 ADD CONSTRAINT `FK_orders_session`
	FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `orders` 
 ADD CONSTRAINT `FK_orders_user`
	FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `sessions` 
 ADD CONSTRAINT `FK_sessions_shops`
	FOREIGN KEY (`shop_id`) REFERENCES `shops` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `sessions` 
 ADD CONSTRAINT `FK_sessions_users`
	FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;
